### PR TITLE
Viral replication update

### PR DESCRIPTION
**Pull request by ASinanSaglam**
Creating the pull request to discuss the changes and talk about what else that might need to be done. 

- Added RNA replication and degradation 

- Added a viral replication test configuration XML that turns off immune system and changes 3 parameters

- Added a couple scripts to run tests and do basic plotting.

A couple questions, where should the scripts and separate config XMLs be placed? Currently they are sitting along with the regular config XMLs and I made a separate folder named scripts but it probably should have more hierarchy than what I placed there. 

Additionally, I could make the scripts better for more general purpose use but at the moment they are pretty hardcoded to do one thing. If you give me descriptions of what you want the scripts to do I could generalize them further. At the moment one scripts just does a MOI scan and pulls some data from the output and the plotting just pulls the data in and does plotting. Data that's pulled is saved as basic python pickles, this could also be improved as an numpy pickles or better yet as H5 files.

### CODE REVIEW

**Comment by ASinanSaglam** [comment]
Just an update, please don't accept this just now, I'm testing changes to assembled virion export that we discussed with @MathCancer 10/20/2020.

**Comment by MathCancer** [comment]
how are things looking Sinan?

**Comment by ASinanSaglam** [comment]
I have fixed things to work with the latest export changes and everything makes sense to me right now. I'm working on a Jupyter notebook to compare to the ODE model we have and we'll parametrize to match that ASAP. 

I just caught a mistake in my implementation thanks to that notebook and that's fixed in the last commit. I was removing uncoated virions _after_ the viral replication step which was causing it to deplete early (and go to negative values), that step is moved before the amplification step and the mass conservation check is back in at the appropriate step.

**Comment by ASinanSaglam** [comment]
OK, I validated the model for the most part but there is one small issue I don't quite understand. Everything in the model until virions are converted to viral RNAs match but viral proteins and assembled proteins are a bit off and the virions in the virion field is also slightly off. I suspect this is somehow due to different ways of counting the variables but I'm really not sure. 

For reference, these simulations are immune system off, virion update off, each cell is started at X virions per cell where X is 50, 10 and 1 which are the different lines in these plots. Same rate constants and initial states for both the PhysiCell simulations and the ODE calculations. 

image
image
image

I did a small scan of the viral protein production rate and found that changing that rate constant can make the viral protein count match but it throws off the environmental virion count by 100s. Weird thing is that, PhysiCell results are _behind_ ~6 virions/proteins per cell in viral protein count and assembled virion count but is _ahead_ by 10-20 virions per cell in the exported virion count in these tests. So upping the viral protein production rate makes the discrepancy in the virion field even worse. 

Having said that, from the tests I ran, I really suspect there is just some counting difference that I'm not sure of. The equations look right, everything before the proteins match and the discrepancy is relatively small (not small enough that it's an integration error but still). I would really like to figure out where this is coming from but even if we didn't the viral replication seems like it's relatively close to the ODE model we have.

**Pull request merged**
